stages:
  train:
    cmd: python train.py
    deps:
    - users.csv
    - train.py
    - mymodel.py
    - elog
    params:
    - epochs
    - log_file
    - dvc_logs_dir
    - dropout
    outs:
    - logs
    - dvc_logs
    metrics:
    - summary.json:
        cache: false
    - cust_metr.json:
        cache: false
    plots:
    - logs.csv:
        cache: false
